# Generated by Django 2.2.4 on 2019-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='タスク')),
                ('complete_flag', models.BooleanField(verbose_name='完了フラグ')),
                ('created_date', models.DateField(verbose_name='登録日付')),
                ('created_by', models.CharField(max_length=100, verbose_name='登録者')),
            ],
        ),
    ]
